import type {
  ColSpanToken,
  ColStartToken,
  ColumnsToken,
  RowSpanToken,
  RowsToken,
} from "../types"

export const gridVariants = {
  columns: {
    none: "grid-cols-none",
    "1": "grid-cols-1",
    "2": "grid-cols-2",
    "3": "grid-cols-3",
    "4": "grid-cols-4",
    "5": "grid-cols-5",
    "6": "grid-cols-6",
    "7": "grid-cols-7",
    "8": "grid-cols-8",
    "9": "grid-cols-9",
    "10": "grid-cols-10",
    "11": "grid-cols-11",
    "12": "grid-cols-12",
  } satisfies Record<ColumnsToken, string>,

  rows: {
    none: "grid-rows-none",
    "1": "grid-rows-1",
    "2": "grid-rows-2",
    "3": "grid-rows-3",
    "4": "grid-rows-4",
    "5": "grid-rows-5",
    "6": "grid-rows-6",
  } satisfies Record<RowsToken, string>,

  colSpan: {
    "1": "col-span-1",
    "2": "col-span-2",
    "3": "col-span-3",
    "4": "col-span-4",
    "5": "col-span-5",
    "6": "col-span-6",
    "7": "col-span-7",
    "8": "col-span-8",
    "9": "col-span-9",
    "10": "col-span-10",
    "11": "col-span-11",
    "12": "col-span-12",
    full: "col-span-full",
  } satisfies Record<ColSpanToken, string>,

  colStart: {
    auto: "col-start-auto",
    "1": "col-start-1",
    "2": "col-start-2",
    "3": "col-start-3",
    "4": "col-start-4",
    "5": "col-start-5",
    "6": "col-start-6",
    "7": "col-start-7",
    "8": "col-start-8",
    "9": "col-start-9",
    "10": "col-start-10",
    "11": "col-start-11",
    "12": "col-start-12",
    "13": "col-start-13",
  } satisfies Record<ColStartToken, string>,

  rowSpan: {
    "1": "row-span-1",
    "2": "row-span-2",
    "3": "row-span-3",
    "4": "row-span-4",
    "5": "row-span-5",
    "6": "row-span-6",
    full: "row-span-full",
  } satisfies Record<RowSpanToken, string>,
}
