/**
 * Responsive class safelist for F0Box.
 *
 * Tailwind's JIT scanner detects these literal class strings in the source
 * and generates the corresponding CSS. This ensures that dynamically
 * prefixed responsive classes (sm:*, md:*, lg:*, xl:*) work at runtime.
 *
 * DO NOT REMOVE — required for F0Box responsive props (sm, md, lg, xl).
 */

// prettier-ignore
export const RESPONSIVE_SAFELIST = [
  // ===================== DISPLAY =====================
  "sm:block", "sm:flex", "sm:inline", "sm:inline-flex", "sm:grid", "sm:hidden",
  "md:block", "md:flex", "md:inline", "md:inline-flex", "md:grid", "md:hidden",
  "lg:block", "lg:flex", "lg:inline", "lg:inline-flex", "lg:grid", "lg:hidden",
  "xl:block", "xl:flex", "xl:inline", "xl:inline-flex", "xl:grid", "xl:hidden",

  // ===================== PADDING (none=p-0, xs=p-1, sm=p-2, md=p-3, lg=p-4, xl=p-6, 2xl=p-8, 3xl=p-10, 4xl=p-12, 5xl=p-16) =====================
  "sm:p-0", "sm:p-1", "sm:p-2", "sm:p-3", "sm:p-4", "sm:p-6", "sm:p-8", "sm:p-10", "sm:p-12", "sm:p-16",
  "sm:px-0", "sm:px-1", "sm:px-2", "sm:px-3", "sm:px-4", "sm:px-6", "sm:px-8", "sm:px-10", "sm:px-12", "sm:px-16",
  "sm:py-0", "sm:py-1", "sm:py-2", "sm:py-3", "sm:py-4", "sm:py-6", "sm:py-8", "sm:py-10", "sm:py-12", "sm:py-16",
  "sm:pt-0", "sm:pt-1", "sm:pt-2", "sm:pt-3", "sm:pt-4", "sm:pt-6", "sm:pt-8", "sm:pt-10", "sm:pt-12", "sm:pt-16",
  "sm:pb-0", "sm:pb-1", "sm:pb-2", "sm:pb-3", "sm:pb-4", "sm:pb-6", "sm:pb-8", "sm:pb-10", "sm:pb-12", "sm:pb-16",
  "sm:pl-0", "sm:pl-1", "sm:pl-2", "sm:pl-3", "sm:pl-4", "sm:pl-6", "sm:pl-8", "sm:pl-10", "sm:pl-12", "sm:pl-16",
  "sm:pr-0", "sm:pr-1", "sm:pr-2", "sm:pr-3", "sm:pr-4", "sm:pr-6", "sm:pr-8", "sm:pr-10", "sm:pr-12", "sm:pr-16",
  "md:p-0", "md:p-1", "md:p-2", "md:p-3", "md:p-4", "md:p-6", "md:p-8", "md:p-10", "md:p-12", "md:p-16",
  "md:px-0", "md:px-1", "md:px-2", "md:px-3", "md:px-4", "md:px-6", "md:px-8", "md:px-10", "md:px-12", "md:px-16",
  "md:py-0", "md:py-1", "md:py-2", "md:py-3", "md:py-4", "md:py-6", "md:py-8", "md:py-10", "md:py-12", "md:py-16",
  "md:pt-0", "md:pt-1", "md:pt-2", "md:pt-3", "md:pt-4", "md:pt-6", "md:pt-8", "md:pt-10", "md:pt-12", "md:pt-16",
  "md:pb-0", "md:pb-1", "md:pb-2", "md:pb-3", "md:pb-4", "md:pb-6", "md:pb-8", "md:pb-10", "md:pb-12", "md:pb-16",
  "md:pl-0", "md:pl-1", "md:pl-2", "md:pl-3", "md:pl-4", "md:pl-6", "md:pl-8", "md:pl-10", "md:pl-12", "md:pl-16",
  "md:pr-0", "md:pr-1", "md:pr-2", "md:pr-3", "md:pr-4", "md:pr-6", "md:pr-8", "md:pr-10", "md:pr-12", "md:pr-16",
  "lg:p-0", "lg:p-1", "lg:p-2", "lg:p-3", "lg:p-4", "lg:p-6", "lg:p-8", "lg:p-10", "lg:p-12", "lg:p-16",
  "lg:px-0", "lg:px-1", "lg:px-2", "lg:px-3", "lg:px-4", "lg:px-6", "lg:px-8", "lg:px-10", "lg:px-12", "lg:px-16",
  "lg:py-0", "lg:py-1", "lg:py-2", "lg:py-3", "lg:py-4", "lg:py-6", "lg:py-8", "lg:py-10", "lg:py-12", "lg:py-16",
  "lg:pt-0", "lg:pt-1", "lg:pt-2", "lg:pt-3", "lg:pt-4", "lg:pt-6", "lg:pt-8", "lg:pt-10", "lg:pt-12", "lg:pt-16",
  "lg:pb-0", "lg:pb-1", "lg:pb-2", "lg:pb-3", "lg:pb-4", "lg:pb-6", "lg:pb-8", "lg:pb-10", "lg:pb-12", "lg:pb-16",
  "lg:pl-0", "lg:pl-1", "lg:pl-2", "lg:pl-3", "lg:pl-4", "lg:pl-6", "lg:pl-8", "lg:pl-10", "lg:pl-12", "lg:pl-16",
  "lg:pr-0", "lg:pr-1", "lg:pr-2", "lg:pr-3", "lg:pr-4", "lg:pr-6", "lg:pr-8", "lg:pr-10", "lg:pr-12", "lg:pr-16",
  "xl:p-0", "xl:p-1", "xl:p-2", "xl:p-3", "xl:p-4", "xl:p-6", "xl:p-8", "xl:p-10", "xl:p-12", "xl:p-16",
  "xl:px-0", "xl:px-1", "xl:px-2", "xl:px-3", "xl:px-4", "xl:px-6", "xl:px-8", "xl:px-10", "xl:px-12", "xl:px-16",
  "xl:py-0", "xl:py-1", "xl:py-2", "xl:py-3", "xl:py-4", "xl:py-6", "xl:py-8", "xl:py-10", "xl:py-12", "xl:py-16",
  "xl:pt-0", "xl:pt-1", "xl:pt-2", "xl:pt-3", "xl:pt-4", "xl:pt-6", "xl:pt-8", "xl:pt-10", "xl:pt-12", "xl:pt-16",
  "xl:pb-0", "xl:pb-1", "xl:pb-2", "xl:pb-3", "xl:pb-4", "xl:pb-6", "xl:pb-8", "xl:pb-10", "xl:pb-12", "xl:pb-16",
  "xl:pl-0", "xl:pl-1", "xl:pl-2", "xl:pl-3", "xl:pl-4", "xl:pl-6", "xl:pl-8", "xl:pl-10", "xl:pl-12", "xl:pl-16",
  "xl:pr-0", "xl:pr-1", "xl:pr-2", "xl:pr-3", "xl:pr-4", "xl:pr-6", "xl:pr-8", "xl:pr-10", "xl:pr-12", "xl:pr-16",

  // ===================== MARGIN (none=m-0, xs=m-1, sm=m-2, md=m-3, lg=m-4, xl=m-6, 2xl=m-8, 3xl=m-10, 4xl=m-12, 5xl=m-16) =====================
  "sm:m-0", "sm:m-1", "sm:m-2", "sm:m-3", "sm:m-4", "sm:m-6", "sm:m-8", "sm:m-10", "sm:m-12", "sm:m-16", "sm:m-auto",
  "sm:mx-0", "sm:mx-1", "sm:mx-2", "sm:mx-3", "sm:mx-4", "sm:mx-6", "sm:mx-8", "sm:mx-10", "sm:mx-12", "sm:mx-16", "sm:mx-auto",
  "sm:my-0", "sm:my-1", "sm:my-2", "sm:my-3", "sm:my-4", "sm:my-6", "sm:my-8", "sm:my-10", "sm:my-12", "sm:my-16", "sm:my-auto",
  "sm:mt-0", "sm:mt-1", "sm:mt-2", "sm:mt-3", "sm:mt-4", "sm:mt-6", "sm:mt-8", "sm:mt-10", "sm:mt-12", "sm:mt-16", "sm:mt-auto",
  "sm:mb-0", "sm:mb-1", "sm:mb-2", "sm:mb-3", "sm:mb-4", "sm:mb-6", "sm:mb-8", "sm:mb-10", "sm:mb-12", "sm:mb-16", "sm:mb-auto",
  "sm:ml-0", "sm:ml-1", "sm:ml-2", "sm:ml-3", "sm:ml-4", "sm:ml-6", "sm:ml-8", "sm:ml-10", "sm:ml-12", "sm:ml-16", "sm:ml-auto",
  "sm:mr-0", "sm:mr-1", "sm:mr-2", "sm:mr-3", "sm:mr-4", "sm:mr-6", "sm:mr-8", "sm:mr-10", "sm:mr-12", "sm:mr-16", "sm:mr-auto",
  "md:m-0", "md:m-1", "md:m-2", "md:m-3", "md:m-4", "md:m-6", "md:m-8", "md:m-10", "md:m-12", "md:m-16", "md:m-auto",
  "md:mx-0", "md:mx-1", "md:mx-2", "md:mx-3", "md:mx-4", "md:mx-6", "md:mx-8", "md:mx-10", "md:mx-12", "md:mx-16", "md:mx-auto",
  "md:my-0", "md:my-1", "md:my-2", "md:my-3", "md:my-4", "md:my-6", "md:my-8", "md:my-10", "md:my-12", "md:my-16", "md:my-auto",
  "md:mt-0", "md:mt-1", "md:mt-2", "md:mt-3", "md:mt-4", "md:mt-6", "md:mt-8", "md:mt-10", "md:mt-12", "md:mt-16", "md:mt-auto",
  "md:mb-0", "md:mb-1", "md:mb-2", "md:mb-3", "md:mb-4", "md:mb-6", "md:mb-8", "md:mb-10", "md:mb-12", "md:mb-16", "md:mb-auto",
  "md:ml-0", "md:ml-1", "md:ml-2", "md:ml-3", "md:ml-4", "md:ml-6", "md:ml-8", "md:ml-10", "md:ml-12", "md:ml-16", "md:ml-auto",
  "md:mr-0", "md:mr-1", "md:mr-2", "md:mr-3", "md:mr-4", "md:mr-6", "md:mr-8", "md:mr-10", "md:mr-12", "md:mr-16", "md:mr-auto",
  "lg:m-0", "lg:m-1", "lg:m-2", "lg:m-3", "lg:m-4", "lg:m-6", "lg:m-8", "lg:m-10", "lg:m-12", "lg:m-16", "lg:m-auto",
  "lg:mx-0", "lg:mx-1", "lg:mx-2", "lg:mx-3", "lg:mx-4", "lg:mx-6", "lg:mx-8", "lg:mx-10", "lg:mx-12", "lg:mx-16", "lg:mx-auto",
  "lg:my-0", "lg:my-1", "lg:my-2", "lg:my-3", "lg:my-4", "lg:my-6", "lg:my-8", "lg:my-10", "lg:my-12", "lg:my-16", "lg:my-auto",
  "lg:mt-0", "lg:mt-1", "lg:mt-2", "lg:mt-3", "lg:mt-4", "lg:mt-6", "lg:mt-8", "lg:mt-10", "lg:mt-12", "lg:mt-16", "lg:mt-auto",
  "lg:mb-0", "lg:mb-1", "lg:mb-2", "lg:mb-3", "lg:mb-4", "lg:mb-6", "lg:mb-8", "lg:mb-10", "lg:mb-12", "lg:mb-16", "lg:mb-auto",
  "lg:ml-0", "lg:ml-1", "lg:ml-2", "lg:ml-3", "lg:ml-4", "lg:ml-6", "lg:ml-8", "lg:ml-10", "lg:ml-12", "lg:ml-16", "lg:ml-auto",
  "lg:mr-0", "lg:mr-1", "lg:mr-2", "lg:mr-3", "lg:mr-4", "lg:mr-6", "lg:mr-8", "lg:mr-10", "lg:mr-12", "lg:mr-16", "lg:mr-auto",
  "xl:m-0", "xl:m-1", "xl:m-2", "xl:m-3", "xl:m-4", "xl:m-6", "xl:m-8", "xl:m-10", "xl:m-12", "xl:m-16", "xl:m-auto",
  "xl:mx-0", "xl:mx-1", "xl:mx-2", "xl:mx-3", "xl:mx-4", "xl:mx-6", "xl:mx-8", "xl:mx-10", "xl:mx-12", "xl:mx-16", "xl:mx-auto",
  "xl:my-0", "xl:my-1", "xl:my-2", "xl:my-3", "xl:my-4", "xl:my-6", "xl:my-8", "xl:my-10", "xl:my-12", "xl:my-16", "xl:my-auto",
  "xl:mt-0", "xl:mt-1", "xl:mt-2", "xl:mt-3", "xl:mt-4", "xl:mt-6", "xl:mt-8", "xl:mt-10", "xl:mt-12", "xl:mt-16", "xl:mt-auto",
  "xl:mb-0", "xl:mb-1", "xl:mb-2", "xl:mb-3", "xl:mb-4", "xl:mb-6", "xl:mb-8", "xl:mb-10", "xl:mb-12", "xl:mb-16", "xl:mb-auto",
  "xl:ml-0", "xl:ml-1", "xl:ml-2", "xl:ml-3", "xl:ml-4", "xl:ml-6", "xl:ml-8", "xl:ml-10", "xl:ml-12", "xl:ml-16", "xl:ml-auto",
  "xl:mr-0", "xl:mr-1", "xl:mr-2", "xl:mr-3", "xl:mr-4", "xl:mr-6", "xl:mr-8", "xl:mr-10", "xl:mr-12", "xl:mr-16", "xl:mr-auto",

  // ===================== POSITION =====================
  "sm:static", "sm:relative", "sm:absolute", "sm:fixed", "sm:sticky",
  "md:static", "md:relative", "md:absolute", "md:fixed", "md:sticky",
  "lg:static", "lg:relative", "lg:absolute", "lg:fixed", "lg:sticky",
  "xl:static", "xl:relative", "xl:absolute", "xl:fixed", "xl:sticky",

  // ===================== GAP (none=gap-0, xs=gap-0.5, sm=gap-sm, md=gap-md, lg=gap-lg, xl=gap-xl, 2xl=gap-6, 3xl=gap-8, 4xl=gap-10, 5xl=gap-12) =====================
  "sm:gap-0", "sm:gap-0.5", "sm:gap-1", "sm:gap-2", "sm:gap-3", "sm:gap-4", "sm:gap-6", "sm:gap-8", "sm:gap-10", "sm:gap-12",
  "md:gap-0", "md:gap-0.5", "md:gap-1", "md:gap-2", "md:gap-3", "md:gap-4", "md:gap-6", "md:gap-8", "md:gap-10", "md:gap-12",
  "lg:gap-0", "lg:gap-0.5", "lg:gap-1", "lg:gap-2", "lg:gap-3", "lg:gap-4", "lg:gap-6", "lg:gap-8", "lg:gap-10", "lg:gap-12",
  "xl:gap-0", "xl:gap-0.5", "xl:gap-1", "xl:gap-2", "xl:gap-3", "xl:gap-4", "xl:gap-6", "xl:gap-8", "xl:gap-10", "xl:gap-12",

  // ===================== FLEX =====================
  "sm:items-start", "sm:items-center", "sm:items-end", "sm:items-stretch", "sm:items-baseline",
  "md:items-start", "md:items-center", "md:items-end", "md:items-stretch", "md:items-baseline",
  "lg:items-start", "lg:items-center", "lg:items-end", "lg:items-stretch", "lg:items-baseline",
  "xl:items-start", "xl:items-center", "xl:items-end", "xl:items-stretch", "xl:items-baseline",
  "sm:justify-start", "sm:justify-center", "sm:justify-end", "sm:justify-between", "sm:justify-around", "sm:justify-evenly", "sm:justify-stretch",
  "md:justify-start", "md:justify-center", "md:justify-end", "md:justify-between", "md:justify-around", "md:justify-evenly", "md:justify-stretch",
  "lg:justify-start", "lg:justify-center", "lg:justify-end", "lg:justify-between", "lg:justify-around", "lg:justify-evenly", "lg:justify-stretch",
  "xl:justify-start", "xl:justify-center", "xl:justify-end", "xl:justify-between", "xl:justify-around", "xl:justify-evenly", "xl:justify-stretch",
  "sm:flex-row", "sm:flex-col", "sm:flex-row-reverse", "sm:flex-col-reverse",
  "md:flex-row", "md:flex-col", "md:flex-row-reverse", "md:flex-col-reverse",
  "lg:flex-row", "lg:flex-col", "lg:flex-row-reverse", "lg:flex-col-reverse",
  "xl:flex-row", "xl:flex-col", "xl:flex-row-reverse", "xl:flex-col-reverse",
  "sm:flex-nowrap", "sm:flex-wrap", "sm:flex-wrap-reverse",
  "md:flex-nowrap", "md:flex-wrap", "md:flex-wrap-reverse",
  "lg:flex-nowrap", "lg:flex-wrap", "lg:flex-wrap-reverse",
  "xl:flex-nowrap", "xl:flex-wrap", "xl:flex-wrap-reverse",
  "sm:grow", "sm:grow-0", "sm:shrink", "sm:shrink-0",
  "md:grow", "md:grow-0", "md:shrink", "md:shrink-0",
  "lg:grow", "lg:grow-0", "lg:shrink", "lg:shrink-0",
  "xl:grow", "xl:grow-0", "xl:shrink", "xl:shrink-0",

  // ===================== BACKGROUND =====================
  "sm:bg-transparent", "sm:bg-f1-background", "sm:bg-f1-background-secondary", "sm:bg-f1-background-tertiary",
  "sm:bg-f1-background-inverse", "sm:bg-f1-background-inverse-secondary", "sm:bg-f1-background-bold",
  "sm:bg-f1-background-accent", "sm:bg-f1-background-accent-bold", "sm:bg-f1-background-promote",
  "sm:bg-f1-background-critical", "sm:bg-f1-background-critical-bold",
  "sm:bg-f1-background-info", "sm:bg-f1-background-info-bold",
  "sm:bg-f1-background-warning", "sm:bg-f1-background-warning-bold",
  "sm:bg-f1-background-positive", "sm:bg-f1-background-positive-bold",
  "sm:bg-f1-background-selected", "sm:bg-f1-background-selected-secondary", "sm:bg-f1-background-selected-bold", "sm:bg-f1-background-overlay",
  "md:bg-transparent", "md:bg-f1-background", "md:bg-f1-background-secondary", "md:bg-f1-background-tertiary",
  "md:bg-f1-background-inverse", "md:bg-f1-background-inverse-secondary", "md:bg-f1-background-bold",
  "md:bg-f1-background-accent", "md:bg-f1-background-accent-bold", "md:bg-f1-background-promote",
  "md:bg-f1-background-critical", "md:bg-f1-background-critical-bold",
  "md:bg-f1-background-info", "md:bg-f1-background-info-bold",
  "md:bg-f1-background-warning", "md:bg-f1-background-warning-bold",
  "md:bg-f1-background-positive", "md:bg-f1-background-positive-bold",
  "md:bg-f1-background-selected", "md:bg-f1-background-selected-secondary", "md:bg-f1-background-selected-bold", "md:bg-f1-background-overlay",
  "lg:bg-transparent", "lg:bg-f1-background", "lg:bg-f1-background-secondary", "lg:bg-f1-background-tertiary",
  "lg:bg-f1-background-inverse", "lg:bg-f1-background-inverse-secondary", "lg:bg-f1-background-bold",
  "lg:bg-f1-background-accent", "lg:bg-f1-background-accent-bold", "lg:bg-f1-background-promote",
  "lg:bg-f1-background-critical", "lg:bg-f1-background-critical-bold",
  "lg:bg-f1-background-info", "lg:bg-f1-background-info-bold",
  "lg:bg-f1-background-warning", "lg:bg-f1-background-warning-bold",
  "lg:bg-f1-background-positive", "lg:bg-f1-background-positive-bold",
  "lg:bg-f1-background-selected", "lg:bg-f1-background-selected-secondary", "lg:bg-f1-background-selected-bold", "lg:bg-f1-background-overlay",
  "xl:bg-transparent", "xl:bg-f1-background", "xl:bg-f1-background-secondary", "xl:bg-f1-background-tertiary",
  "xl:bg-f1-background-inverse", "xl:bg-f1-background-inverse-secondary", "xl:bg-f1-background-bold",
  "xl:bg-f1-background-accent", "xl:bg-f1-background-accent-bold", "xl:bg-f1-background-promote",
  "xl:bg-f1-background-critical", "xl:bg-f1-background-critical-bold",
  "xl:bg-f1-background-info", "xl:bg-f1-background-info-bold",
  "xl:bg-f1-background-warning", "xl:bg-f1-background-warning-bold",
  "xl:bg-f1-background-positive", "xl:bg-f1-background-positive-bold",
  "xl:bg-f1-background-selected", "xl:bg-f1-background-selected-secondary", "xl:bg-f1-background-selected-bold", "xl:bg-f1-background-overlay",

  // ===================== BORDER COLOR =====================
  "sm:border-f1-border", "sm:border-f1-border-secondary", "sm:border-f1-border-bold",
  "sm:border-f1-border-selected", "sm:border-f1-border-selected-bold",
  "sm:border-f1-border-critical", "sm:border-f1-border-critical-bold",
  "sm:border-f1-border-warning", "sm:border-f1-border-warning-bold",
  "sm:border-f1-border-info", "sm:border-f1-border-info-bold",
  "sm:border-f1-border-positive", "sm:border-f1-border-positive-bold", "sm:border-f1-border-promote",
  "md:border-f1-border", "md:border-f1-border-secondary", "md:border-f1-border-bold",
  "md:border-f1-border-selected", "md:border-f1-border-selected-bold",
  "md:border-f1-border-critical", "md:border-f1-border-critical-bold",
  "md:border-f1-border-warning", "md:border-f1-border-warning-bold",
  "md:border-f1-border-info", "md:border-f1-border-info-bold",
  "md:border-f1-border-positive", "md:border-f1-border-positive-bold", "md:border-f1-border-promote",
  "lg:border-f1-border", "lg:border-f1-border-secondary", "lg:border-f1-border-bold",
  "lg:border-f1-border-selected", "lg:border-f1-border-selected-bold",
  "lg:border-f1-border-critical", "lg:border-f1-border-critical-bold",
  "lg:border-f1-border-warning", "lg:border-f1-border-warning-bold",
  "lg:border-f1-border-info", "lg:border-f1-border-info-bold",
  "lg:border-f1-border-positive", "lg:border-f1-border-positive-bold", "lg:border-f1-border-promote",
  "xl:border-f1-border", "xl:border-f1-border-secondary", "xl:border-f1-border-bold",
  "xl:border-f1-border-selected", "xl:border-f1-border-selected-bold",
  "xl:border-f1-border-critical", "xl:border-f1-border-critical-bold",
  "xl:border-f1-border-warning", "xl:border-f1-border-warning-bold",
  "xl:border-f1-border-info", "xl:border-f1-border-info-bold",
  "xl:border-f1-border-positive", "xl:border-f1-border-positive-bold", "xl:border-f1-border-promote",

  // ===================== BORDER WIDTH =====================
  "sm:border-0", "sm:border", "sm:border-solid", "sm:border-2",
  "sm:border-t", "sm:border-t-0", "sm:border-t-2",
  "sm:border-b", "sm:border-b-0", "sm:border-b-2",
  "sm:border-l", "sm:border-l-0", "sm:border-l-2",
  "sm:border-r", "sm:border-r-0", "sm:border-r-2",
  "md:border-0", "md:border", "md:border-solid", "md:border-2",
  "md:border-t", "md:border-t-0", "md:border-t-2",
  "md:border-b", "md:border-b-0", "md:border-b-2",
  "md:border-l", "md:border-l-0", "md:border-l-2",
  "md:border-r", "md:border-r-0", "md:border-r-2",
  "lg:border-0", "lg:border", "lg:border-solid", "lg:border-2",
  "lg:border-t", "lg:border-t-0", "lg:border-t-2",
  "lg:border-b", "lg:border-b-0", "lg:border-b-2",
  "lg:border-l", "lg:border-l-0", "lg:border-l-2",
  "lg:border-r", "lg:border-r-0", "lg:border-r-2",
  "xl:border-0", "xl:border", "xl:border-solid", "xl:border-2",
  "xl:border-t", "xl:border-t-0", "xl:border-t-2",
  "xl:border-b", "xl:border-b-0", "xl:border-b-2",
  "xl:border-l", "xl:border-l-0", "xl:border-l-2",
  "xl:border-r", "xl:border-r-0", "xl:border-r-2",

  // ===================== BORDER STYLE =====================
  "sm:border-solid", "sm:border-dashed", "sm:border-dotted", "sm:border-double", "sm:border-none",
  "md:border-solid", "md:border-dashed", "md:border-dotted", "md:border-double", "md:border-none",
  "lg:border-solid", "lg:border-dashed", "lg:border-dotted", "lg:border-double", "lg:border-none",
  "xl:border-solid", "xl:border-dashed", "xl:border-dotted", "xl:border-double", "xl:border-none",

  // ===================== BORDER RADIUS =====================
  "sm:rounded-none", "sm:rounded-2xs", "sm:rounded-xs", "sm:rounded-sm", "sm:rounded-md", "sm:rounded-lg", "sm:rounded-xl", "sm:rounded-2xl", "sm:rounded-full",
  "sm:rounded-tl-none", "sm:rounded-tl-2xs", "sm:rounded-tl-xs", "sm:rounded-tl-sm", "sm:rounded-tl-md", "sm:rounded-tl-lg", "sm:rounded-tl-xl", "sm:rounded-tl-2xl", "sm:rounded-tl-full",
  "sm:rounded-tr-none", "sm:rounded-tr-2xs", "sm:rounded-tr-xs", "sm:rounded-tr-sm", "sm:rounded-tr-md", "sm:rounded-tr-lg", "sm:rounded-tr-xl", "sm:rounded-tr-2xl", "sm:rounded-tr-full",
  "sm:rounded-bl-none", "sm:rounded-bl-2xs", "sm:rounded-bl-xs", "sm:rounded-bl-sm", "sm:rounded-bl-md", "sm:rounded-bl-lg", "sm:rounded-bl-xl", "sm:rounded-bl-2xl", "sm:rounded-bl-full",
  "sm:rounded-br-none", "sm:rounded-br-2xs", "sm:rounded-br-xs", "sm:rounded-br-sm", "sm:rounded-br-md", "sm:rounded-br-lg", "sm:rounded-br-xl", "sm:rounded-br-2xl", "sm:rounded-br-full",
  "md:rounded-none", "md:rounded-2xs", "md:rounded-xs", "md:rounded-sm", "md:rounded-md", "md:rounded-lg", "md:rounded-xl", "md:rounded-2xl", "md:rounded-full",
  "md:rounded-tl-none", "md:rounded-tl-2xs", "md:rounded-tl-xs", "md:rounded-tl-sm", "md:rounded-tl-md", "md:rounded-tl-lg", "md:rounded-tl-xl", "md:rounded-tl-2xl", "md:rounded-tl-full",
  "md:rounded-tr-none", "md:rounded-tr-2xs", "md:rounded-tr-xs", "md:rounded-tr-sm", "md:rounded-tr-md", "md:rounded-tr-lg", "md:rounded-tr-xl", "md:rounded-tr-2xl", "md:rounded-tr-full",
  "md:rounded-bl-none", "md:rounded-bl-2xs", "md:rounded-bl-xs", "md:rounded-bl-sm", "md:rounded-bl-md", "md:rounded-bl-lg", "md:rounded-bl-xl", "md:rounded-bl-2xl", "md:rounded-bl-full",
  "md:rounded-br-none", "md:rounded-br-2xs", "md:rounded-br-xs", "md:rounded-br-sm", "md:rounded-br-md", "md:rounded-br-lg", "md:rounded-br-xl", "md:rounded-br-2xl", "md:rounded-br-full",
  "lg:rounded-none", "lg:rounded-2xs", "lg:rounded-xs", "lg:rounded-sm", "lg:rounded-md", "lg:rounded-lg", "lg:rounded-xl", "lg:rounded-2xl", "lg:rounded-full",
  "lg:rounded-tl-none", "lg:rounded-tl-2xs", "lg:rounded-tl-xs", "lg:rounded-tl-sm", "lg:rounded-tl-md", "lg:rounded-tl-lg", "lg:rounded-tl-xl", "lg:rounded-tl-2xl", "lg:rounded-tl-full",
  "lg:rounded-tr-none", "lg:rounded-tr-2xs", "lg:rounded-tr-xs", "lg:rounded-tr-sm", "lg:rounded-tr-md", "lg:rounded-tr-lg", "lg:rounded-tr-xl", "lg:rounded-tr-2xl", "lg:rounded-tr-full",
  "lg:rounded-bl-none", "lg:rounded-bl-2xs", "lg:rounded-bl-xs", "lg:rounded-bl-sm", "lg:rounded-bl-md", "lg:rounded-bl-lg", "lg:rounded-bl-xl", "lg:rounded-bl-2xl", "lg:rounded-bl-full",
  "lg:rounded-br-none", "lg:rounded-br-2xs", "lg:rounded-br-xs", "lg:rounded-br-sm", "lg:rounded-br-md", "lg:rounded-br-lg", "lg:rounded-br-xl", "lg:rounded-br-2xl", "lg:rounded-br-full",
  "xl:rounded-none", "xl:rounded-2xs", "xl:rounded-xs", "xl:rounded-sm", "xl:rounded-md", "xl:rounded-lg", "xl:rounded-xl", "xl:rounded-2xl", "xl:rounded-full",
  "xl:rounded-tl-none", "xl:rounded-tl-2xs", "xl:rounded-tl-xs", "xl:rounded-tl-sm", "xl:rounded-tl-md", "xl:rounded-tl-lg", "xl:rounded-tl-xl", "xl:rounded-tl-2xl", "xl:rounded-tl-full",
  "xl:rounded-tr-none", "xl:rounded-tr-2xs", "xl:rounded-tr-xs", "xl:rounded-tr-sm", "xl:rounded-tr-md", "xl:rounded-tr-lg", "xl:rounded-tr-xl", "xl:rounded-tr-2xl", "xl:rounded-tr-full",
  "xl:rounded-bl-none", "xl:rounded-bl-2xs", "xl:rounded-bl-xs", "xl:rounded-bl-sm", "xl:rounded-bl-md", "xl:rounded-bl-lg", "xl:rounded-bl-xl", "xl:rounded-bl-2xl", "xl:rounded-bl-full",
  "xl:rounded-br-none", "xl:rounded-br-2xs", "xl:rounded-br-xs", "xl:rounded-br-sm", "xl:rounded-br-md", "xl:rounded-br-lg", "xl:rounded-br-xl", "xl:rounded-br-2xl", "xl:rounded-br-full",

  // ===================== OVERFLOW =====================
  "sm:overflow-visible", "sm:overflow-hidden", "sm:overflow-auto", "sm:overflow-scroll",
  "sm:overflow-x-visible", "sm:overflow-x-hidden", "sm:overflow-x-auto", "sm:overflow-x-scroll",
  "sm:overflow-y-visible", "sm:overflow-y-hidden", "sm:overflow-y-auto", "sm:overflow-y-scroll",
  "md:overflow-visible", "md:overflow-hidden", "md:overflow-auto", "md:overflow-scroll",
  "md:overflow-x-visible", "md:overflow-x-hidden", "md:overflow-x-auto", "md:overflow-x-scroll",
  "md:overflow-y-visible", "md:overflow-y-hidden", "md:overflow-y-auto", "md:overflow-y-scroll",
  "lg:overflow-visible", "lg:overflow-hidden", "lg:overflow-auto", "lg:overflow-scroll",
  "lg:overflow-x-visible", "lg:overflow-x-hidden", "lg:overflow-x-auto", "lg:overflow-x-scroll",
  "lg:overflow-y-visible", "lg:overflow-y-hidden", "lg:overflow-y-auto", "lg:overflow-y-scroll",
  "xl:overflow-visible", "xl:overflow-hidden", "xl:overflow-auto", "xl:overflow-scroll",
  "xl:overflow-x-visible", "xl:overflow-x-hidden", "xl:overflow-x-auto", "xl:overflow-x-scroll",
  "xl:overflow-y-visible", "xl:overflow-y-hidden", "xl:overflow-y-auto", "xl:overflow-y-scroll",

  // ===================== DIVIDER =====================
  "sm:divide-x", "sm:divide-y", "sm:divide-x-0", "sm:divide-y-0", "sm:divide-solid",
  "md:divide-x", "md:divide-y", "md:divide-x-0", "md:divide-y-0", "md:divide-solid",
  "lg:divide-x", "lg:divide-y", "lg:divide-x-0", "lg:divide-y-0", "lg:divide-solid",
  "xl:divide-x", "xl:divide-y", "xl:divide-x-0", "xl:divide-y-0", "xl:divide-solid",
  "sm:divide-f1-border", "sm:divide-f1-border-secondary", "sm:divide-f1-border-bold",
  "sm:divide-f1-border-selected", "sm:divide-f1-border-selected-bold",
  "sm:divide-f1-border-critical", "sm:divide-f1-border-critical-bold",
  "sm:divide-f1-border-warning", "sm:divide-f1-border-warning-bold",
  "sm:divide-f1-border-info", "sm:divide-f1-border-info-bold",
  "sm:divide-f1-border-positive", "sm:divide-f1-border-positive-bold", "sm:divide-f1-border-promote",
  "md:divide-f1-border", "md:divide-f1-border-secondary", "md:divide-f1-border-bold",
  "md:divide-f1-border-selected", "md:divide-f1-border-selected-bold",
  "md:divide-f1-border-critical", "md:divide-f1-border-critical-bold",
  "md:divide-f1-border-warning", "md:divide-f1-border-warning-bold",
  "md:divide-f1-border-info", "md:divide-f1-border-info-bold",
  "md:divide-f1-border-positive", "md:divide-f1-border-positive-bold", "md:divide-f1-border-promote",
  "lg:divide-f1-border", "lg:divide-f1-border-secondary", "lg:divide-f1-border-bold",
  "lg:divide-f1-border-selected", "lg:divide-f1-border-selected-bold",
  "lg:divide-f1-border-critical", "lg:divide-f1-border-critical-bold",
  "lg:divide-f1-border-warning", "lg:divide-f1-border-warning-bold",
  "lg:divide-f1-border-info", "lg:divide-f1-border-info-bold",
  "lg:divide-f1-border-positive", "lg:divide-f1-border-positive-bold", "lg:divide-f1-border-promote",
  "xl:divide-f1-border", "xl:divide-f1-border-secondary", "xl:divide-f1-border-bold",
  "xl:divide-f1-border-selected", "xl:divide-f1-border-selected-bold",
  "xl:divide-f1-border-critical", "xl:divide-f1-border-critical-bold",
  "xl:divide-f1-border-warning", "xl:divide-f1-border-warning-bold",
  "xl:divide-f1-border-info", "xl:divide-f1-border-info-bold",
  "xl:divide-f1-border-positive", "xl:divide-f1-border-positive-bold", "xl:divide-f1-border-promote",

  // ===================== GRID =====================
  "sm:grid-cols-none", "sm:grid-cols-1", "sm:grid-cols-2", "sm:grid-cols-3", "sm:grid-cols-4", "sm:grid-cols-5", "sm:grid-cols-6",
  "sm:grid-cols-7", "sm:grid-cols-8", "sm:grid-cols-9", "sm:grid-cols-10", "sm:grid-cols-11", "sm:grid-cols-12",
  "md:grid-cols-none", "md:grid-cols-1", "md:grid-cols-2", "md:grid-cols-3", "md:grid-cols-4", "md:grid-cols-5", "md:grid-cols-6",
  "md:grid-cols-7", "md:grid-cols-8", "md:grid-cols-9", "md:grid-cols-10", "md:grid-cols-11", "md:grid-cols-12",
  "lg:grid-cols-none", "lg:grid-cols-1", "lg:grid-cols-2", "lg:grid-cols-3", "lg:grid-cols-4", "lg:grid-cols-5", "lg:grid-cols-6",
  "lg:grid-cols-7", "lg:grid-cols-8", "lg:grid-cols-9", "lg:grid-cols-10", "lg:grid-cols-11", "lg:grid-cols-12",
  "xl:grid-cols-none", "xl:grid-cols-1", "xl:grid-cols-2", "xl:grid-cols-3", "xl:grid-cols-4", "xl:grid-cols-5", "xl:grid-cols-6",
  "xl:grid-cols-7", "xl:grid-cols-8", "xl:grid-cols-9", "xl:grid-cols-10", "xl:grid-cols-11", "xl:grid-cols-12",
  "sm:grid-rows-none", "sm:grid-rows-1", "sm:grid-rows-2", "sm:grid-rows-3", "sm:grid-rows-4", "sm:grid-rows-5", "sm:grid-rows-6",
  "md:grid-rows-none", "md:grid-rows-1", "md:grid-rows-2", "md:grid-rows-3", "md:grid-rows-4", "md:grid-rows-5", "md:grid-rows-6",
  "lg:grid-rows-none", "lg:grid-rows-1", "lg:grid-rows-2", "lg:grid-rows-3", "lg:grid-rows-4", "lg:grid-rows-5", "lg:grid-rows-6",
  "xl:grid-rows-none", "xl:grid-rows-1", "xl:grid-rows-2", "xl:grid-rows-3", "xl:grid-rows-4", "xl:grid-rows-5", "xl:grid-rows-6",
  "sm:col-span-1", "sm:col-span-2", "sm:col-span-3", "sm:col-span-4", "sm:col-span-5", "sm:col-span-6",
  "sm:col-span-7", "sm:col-span-8", "sm:col-span-9", "sm:col-span-10", "sm:col-span-11", "sm:col-span-12", "sm:col-span-full",
  "md:col-span-1", "md:col-span-2", "md:col-span-3", "md:col-span-4", "md:col-span-5", "md:col-span-6",
  "md:col-span-7", "md:col-span-8", "md:col-span-9", "md:col-span-10", "md:col-span-11", "md:col-span-12", "md:col-span-full",
  "lg:col-span-1", "lg:col-span-2", "lg:col-span-3", "lg:col-span-4", "lg:col-span-5", "lg:col-span-6",
  "lg:col-span-7", "lg:col-span-8", "lg:col-span-9", "lg:col-span-10", "lg:col-span-11", "lg:col-span-12", "lg:col-span-full",
  "xl:col-span-1", "xl:col-span-2", "xl:col-span-3", "xl:col-span-4", "xl:col-span-5", "xl:col-span-6",
  "xl:col-span-7", "xl:col-span-8", "xl:col-span-9", "xl:col-span-10", "xl:col-span-11", "xl:col-span-12", "xl:col-span-full",
  "sm:col-start-auto", "sm:col-start-1", "sm:col-start-2", "sm:col-start-3", "sm:col-start-4", "sm:col-start-5", "sm:col-start-6",
  "sm:col-start-7", "sm:col-start-8", "sm:col-start-9", "sm:col-start-10", "sm:col-start-11", "sm:col-start-12", "sm:col-start-13",
  "md:col-start-auto", "md:col-start-1", "md:col-start-2", "md:col-start-3", "md:col-start-4", "md:col-start-5", "md:col-start-6",
  "md:col-start-7", "md:col-start-8", "md:col-start-9", "md:col-start-10", "md:col-start-11", "md:col-start-12", "md:col-start-13",
  "lg:col-start-auto", "lg:col-start-1", "lg:col-start-2", "lg:col-start-3", "lg:col-start-4", "lg:col-start-5", "lg:col-start-6",
  "lg:col-start-7", "lg:col-start-8", "lg:col-start-9", "lg:col-start-10", "lg:col-start-11", "lg:col-start-12", "lg:col-start-13",
  "xl:col-start-auto", "xl:col-start-1", "xl:col-start-2", "xl:col-start-3", "xl:col-start-4", "xl:col-start-5", "xl:col-start-6",
  "xl:col-start-7", "xl:col-start-8", "xl:col-start-9", "xl:col-start-10", "xl:col-start-11", "xl:col-start-12", "xl:col-start-13",
  "sm:row-span-1", "sm:row-span-2", "sm:row-span-3", "sm:row-span-4", "sm:row-span-5", "sm:row-span-6", "sm:row-span-full",
  "md:row-span-1", "md:row-span-2", "md:row-span-3", "md:row-span-4", "md:row-span-5", "md:row-span-6", "md:row-span-full",
  "lg:row-span-1", "lg:row-span-2", "lg:row-span-3", "lg:row-span-4", "lg:row-span-5", "lg:row-span-6", "lg:row-span-full",
  "xl:row-span-1", "xl:row-span-2", "xl:row-span-3", "xl:row-span-4", "xl:row-span-5", "xl:row-span-6", "xl:row-span-full",

  // ===================== DIMENSIONS (width) =====================
  "sm:w-auto", "sm:w-full", "sm:w-screen", "sm:w-min", "sm:w-max", "sm:w-fit",
  "sm:w-0", "sm:w-0.5", "sm:w-1", "sm:w-1.5", "sm:w-2", "sm:w-2.5", "sm:w-3", "sm:w-3.5",
  "sm:w-4", "sm:w-5", "sm:w-6", "sm:w-7", "sm:w-8", "sm:w-9", "sm:w-10", "sm:w-11", "sm:w-12",
  "sm:w-14", "sm:w-16", "sm:w-18", "sm:w-20", "sm:w-24", "sm:w-28", "sm:w-32", "sm:w-36",
  "sm:w-40", "sm:w-44", "sm:w-48", "sm:w-52", "sm:w-56", "sm:w-60", "sm:w-64", "sm:w-72", "sm:w-80", "sm:w-96",
  "sm:w-1/2", "sm:w-1/3", "sm:w-2/3", "sm:w-1/4", "sm:w-2/4", "sm:w-3/4",
  "sm:w-1/5", "sm:w-2/5", "sm:w-3/5", "sm:w-4/5", "sm:w-1/6", "sm:w-5/6",
  "md:w-auto", "md:w-full", "md:w-screen", "md:w-min", "md:w-max", "md:w-fit",
  "md:w-0", "md:w-0.5", "md:w-1", "md:w-1.5", "md:w-2", "md:w-2.5", "md:w-3", "md:w-3.5",
  "md:w-4", "md:w-5", "md:w-6", "md:w-7", "md:w-8", "md:w-9", "md:w-10", "md:w-11", "md:w-12",
  "md:w-14", "md:w-16", "md:w-18", "md:w-20", "md:w-24", "md:w-28", "md:w-32", "md:w-36",
  "md:w-40", "md:w-44", "md:w-48", "md:w-52", "md:w-56", "md:w-60", "md:w-64", "md:w-72", "md:w-80", "md:w-96",
  "md:w-1/2", "md:w-1/3", "md:w-2/3", "md:w-1/4", "md:w-2/4", "md:w-3/4",
  "md:w-1/5", "md:w-2/5", "md:w-3/5", "md:w-4/5", "md:w-1/6", "md:w-5/6",
  "lg:w-auto", "lg:w-full", "lg:w-screen", "lg:w-min", "lg:w-max", "lg:w-fit",
  "lg:w-0", "lg:w-0.5", "lg:w-1", "lg:w-1.5", "lg:w-2", "lg:w-2.5", "lg:w-3", "lg:w-3.5",
  "lg:w-4", "lg:w-5", "lg:w-6", "lg:w-7", "lg:w-8", "lg:w-9", "lg:w-10", "lg:w-11", "lg:w-12",
  "lg:w-14", "lg:w-16", "lg:w-18", "lg:w-20", "lg:w-24", "lg:w-28", "lg:w-32", "lg:w-36",
  "lg:w-40", "lg:w-44", "lg:w-48", "lg:w-52", "lg:w-56", "lg:w-60", "lg:w-64", "lg:w-72", "lg:w-80", "lg:w-96",
  "lg:w-1/2", "lg:w-1/3", "lg:w-2/3", "lg:w-1/4", "lg:w-2/4", "lg:w-3/4",
  "lg:w-1/5", "lg:w-2/5", "lg:w-3/5", "lg:w-4/5", "lg:w-1/6", "lg:w-5/6",
  "xl:w-auto", "xl:w-full", "xl:w-screen", "xl:w-min", "xl:w-max", "xl:w-fit",
  "xl:w-0", "xl:w-0.5", "xl:w-1", "xl:w-1.5", "xl:w-2", "xl:w-2.5", "xl:w-3", "xl:w-3.5",
  "xl:w-4", "xl:w-5", "xl:w-6", "xl:w-7", "xl:w-8", "xl:w-9", "xl:w-10", "xl:w-11", "xl:w-12",
  "xl:w-14", "xl:w-16", "xl:w-18", "xl:w-20", "xl:w-24", "xl:w-28", "xl:w-32", "xl:w-36",
  "xl:w-40", "xl:w-44", "xl:w-48", "xl:w-52", "xl:w-56", "xl:w-60", "xl:w-64", "xl:w-72", "xl:w-80", "xl:w-96",
  "xl:w-1/2", "xl:w-1/3", "xl:w-2/3", "xl:w-1/4", "xl:w-2/4", "xl:w-3/4",
  "xl:w-1/5", "xl:w-2/5", "xl:w-3/5", "xl:w-4/5", "xl:w-1/6", "xl:w-5/6",

  // ===================== DIMENSIONS (height) =====================
  "sm:h-auto", "sm:h-full", "sm:h-screen", "sm:h-min", "sm:h-max", "sm:h-fit",
  "sm:h-0", "sm:h-0.5", "sm:h-1", "sm:h-1.5", "sm:h-2", "sm:h-2.5", "sm:h-3", "sm:h-3.5",
  "sm:h-4", "sm:h-5", "sm:h-6", "sm:h-7", "sm:h-8", "sm:h-9", "sm:h-10", "sm:h-11", "sm:h-12",
  "sm:h-14", "sm:h-16", "sm:h-18", "sm:h-20", "sm:h-24", "sm:h-28", "sm:h-32", "sm:h-36",
  "sm:h-40", "sm:h-44", "sm:h-48", "sm:h-52", "sm:h-56", "sm:h-60", "sm:h-64", "sm:h-72", "sm:h-80", "sm:h-96",
  "sm:h-1/2", "sm:h-1/3", "sm:h-2/3", "sm:h-1/4", "sm:h-2/4", "sm:h-3/4",
  "sm:h-1/5", "sm:h-2/5", "sm:h-3/5", "sm:h-4/5", "sm:h-1/6", "sm:h-5/6",
  "md:h-auto", "md:h-full", "md:h-screen", "md:h-min", "md:h-max", "md:h-fit",
  "md:h-0", "md:h-0.5", "md:h-1", "md:h-1.5", "md:h-2", "md:h-2.5", "md:h-3", "md:h-3.5",
  "md:h-4", "md:h-5", "md:h-6", "md:h-7", "md:h-8", "md:h-9", "md:h-10", "md:h-11", "md:h-12",
  "md:h-14", "md:h-16", "md:h-18", "md:h-20", "md:h-24", "md:h-28", "md:h-32", "md:h-36",
  "md:h-40", "md:h-44", "md:h-48", "md:h-52", "md:h-56", "md:h-60", "md:h-64", "md:h-72", "md:h-80", "md:h-96",
  "md:h-1/2", "md:h-1/3", "md:h-2/3", "md:h-1/4", "md:h-2/4", "md:h-3/4",
  "md:h-1/5", "md:h-2/5", "md:h-3/5", "md:h-4/5", "md:h-1/6", "md:h-5/6",
  "lg:h-auto", "lg:h-full", "lg:h-screen", "lg:h-min", "lg:h-max", "lg:h-fit",
  "lg:h-0", "lg:h-0.5", "lg:h-1", "lg:h-1.5", "lg:h-2", "lg:h-2.5", "lg:h-3", "lg:h-3.5",
  "lg:h-4", "lg:h-5", "lg:h-6", "lg:h-7", "lg:h-8", "lg:h-9", "lg:h-10", "lg:h-11", "lg:h-12",
  "lg:h-14", "lg:h-16", "lg:h-18", "lg:h-20", "lg:h-24", "lg:h-28", "lg:h-32", "lg:h-36",
  "lg:h-40", "lg:h-44", "lg:h-48", "lg:h-52", "lg:h-56", "lg:h-60", "lg:h-64", "lg:h-72", "lg:h-80", "lg:h-96",
  "lg:h-1/2", "lg:h-1/3", "lg:h-2/3", "lg:h-1/4", "lg:h-2/4", "lg:h-3/4",
  "lg:h-1/5", "lg:h-2/5", "lg:h-3/5", "lg:h-4/5", "lg:h-1/6", "lg:h-5/6",
  "xl:h-auto", "xl:h-full", "xl:h-screen", "xl:h-min", "xl:h-max", "xl:h-fit",
  "xl:h-0", "xl:h-0.5", "xl:h-1", "xl:h-1.5", "xl:h-2", "xl:h-2.5", "xl:h-3", "xl:h-3.5",
  "xl:h-4", "xl:h-5", "xl:h-6", "xl:h-7", "xl:h-8", "xl:h-9", "xl:h-10", "xl:h-11", "xl:h-12",
  "xl:h-14", "xl:h-16", "xl:h-18", "xl:h-20", "xl:h-24", "xl:h-28", "xl:h-32", "xl:h-36",
  "xl:h-40", "xl:h-44", "xl:h-48", "xl:h-52", "xl:h-56", "xl:h-60", "xl:h-64", "xl:h-72", "xl:h-80", "xl:h-96",
  "xl:h-1/2", "xl:h-1/3", "xl:h-2/3", "xl:h-1/4", "xl:h-2/4", "xl:h-3/4",
  "xl:h-1/5", "xl:h-2/5", "xl:h-3/5", "xl:h-4/5", "xl:h-1/6", "xl:h-5/6",

  // ===================== DIMENSIONS (min-width) =====================
  "sm:min-w-0", "sm:min-w-full", "sm:min-w-min", "sm:min-w-max", "sm:min-w-fit",
  "md:min-w-0", "md:min-w-full", "md:min-w-min", "md:min-w-max", "md:min-w-fit",
  "lg:min-w-0", "lg:min-w-full", "lg:min-w-min", "lg:min-w-max", "lg:min-w-fit",
  "xl:min-w-0", "xl:min-w-full", "xl:min-w-min", "xl:min-w-max", "xl:min-w-fit",

  // ===================== DIMENSIONS (min-height) =====================
  "sm:min-h-0", "sm:min-h-full", "sm:min-h-screen", "sm:min-h-min", "sm:min-h-max", "sm:min-h-fit",
  "md:min-h-0", "md:min-h-full", "md:min-h-screen", "md:min-h-min", "md:min-h-max", "md:min-h-fit",
  "lg:min-h-0", "lg:min-h-full", "lg:min-h-screen", "lg:min-h-min", "lg:min-h-max", "lg:min-h-fit",
  "xl:min-h-0", "xl:min-h-full", "xl:min-h-screen", "xl:min-h-min", "xl:min-h-max", "xl:min-h-fit",

  // ===================== DIMENSIONS (max-width) =====================
  "sm:max-w-none", "sm:max-w-full", "sm:max-w-screen", "sm:max-w-min", "sm:max-w-max", "sm:max-w-fit",
  "md:max-w-none", "md:max-w-full", "md:max-w-screen", "md:max-w-min", "md:max-w-max", "md:max-w-fit",
  "lg:max-w-none", "lg:max-w-full", "lg:max-w-screen", "lg:max-w-min", "lg:max-w-max", "lg:max-w-fit",
  "xl:max-w-none", "xl:max-w-full", "xl:max-w-screen", "xl:max-w-min", "xl:max-w-max", "xl:max-w-fit",

  // ===================== DIMENSIONS (max-height) =====================
  "sm:max-h-none", "sm:max-h-full", "sm:max-h-screen", "sm:max-h-min", "sm:max-h-max", "sm:max-h-fit",
  "md:max-h-none", "md:max-h-full", "md:max-h-screen", "md:max-h-min", "md:max-h-max", "md:max-h-fit",
  "lg:max-h-none", "lg:max-h-full", "lg:max-h-screen", "lg:max-h-min", "lg:max-h-max", "lg:max-h-fit",
  "xl:max-h-none", "xl:max-h-full", "xl:max-h-screen", "xl:max-h-min", "xl:max-h-max", "xl:max-h-fit",
] as const
